type UserResponse {
    id: ID!
    email: String!
    fullName: String!
    roles: [String!]!
    permissions: [String!]!
    createdAt: String
}

type UserPage {
    content: [UserResponse!]!
    totalPages: Int!
    totalElements: Float!
    size: Int!
    number: Int!
    last: Boolean!
    first: Boolean!
}

input RegistrationRequest {
    fullName: String!
    email: String!
    password: String!
}

input LoginRequest {
    email: String!
    password: String!
}

type AuthResponse {
    message: String
    user: UserResponse
}

type Query {
    getMyProfile: UserResponse

    getAllUsers(page: Int = 0, size: Int = 10): UserPage
}

type Mutation {
    register(request: RegistrationRequest!): UserResponse

    login(request: LoginRequest!): AuthResponse

    logout: String
}