server:
  port: 8082
  servlet:
    session:
      cookie:
        name: IDENTITY_SESSION

spring:
  application:
    name: candidate-service
  cloud:
    compatibility-verifier:
      enabled: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    resources:
      static-locations: file:/opt/uploads/resumes/, classpath:/static/

  datasource:
    url: jdbc:postgresql://localhost:5433/interview_db
    username: namdx
    password: password123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: candidate_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    create-schemas: true
    schemas: candidate_schema
    default-schema: candidate_schema
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  session:
    store-type: redis
    redis:
      namespace: "interview:session"
      flush-mode: on_save
      save-mode: always

  graphql:
    show-exceptions: true
    graphiql:
      enabled: true
    schema:
      introspection:
        enabled: true
      locations: "classpath:graphql/"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true