server:
  port: 8082

spring:
  application:
    name: candidate-service
  cloud:
    compatibility-verifier:
      enabled: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    resources:
      static-locations: file:/opt/uploads/resumes/, classpath:/static/

  datasource:
    url: jdbc:postgresql://localhost:5433/interview_db
    username: namdx
    password: password123

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: candidate_schema

  flyway:
    enabled: true
    create-schemas: true
    schemas: candidate_schema
    default-schema: candidate_schema
    locations: classpath:db/migration

dgs:
  graphql:
    path: /graphql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/