-- Create Job Descriptions table
CREATE TABLE job_descriptions (
    id UUID PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    core_skills TEXT[] -- Array of required skills extracted by AI
);

-- Create Interview Sessions table
CREATE TABLE interview_sessions (
    id UUID PRIMARY KEY,
    candidate_id UUID NOT NULL, -- Logical FK to Candidate Service
    jd_id UUID REFERENCES job_descriptions(id),
    recruiter_id UUID NOT NULL, -- Logical FK to Identity Service
    status VARCHAR(20) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create Interview Questions table
CREATE TABLE interview_questions (
    id UUID PRIMARY KEY,
    session_id UUID REFERENCES interview_sessions(id) ON DELETE CASCADE,
    question_text TEXT NOT NULL,
    expected_answer TEXT,
    ai_generated BOOLEAN DEFAULT TRUE
);

-- Create Interview Evaluations table
CREATE TABLE interview_evaluations (
    id UUID PRIMARY KEY,
    question_id UUID REFERENCES interview_questions(id) ON DELETE CASCADE,
    candidate_answer TEXT,
    score INTEGER CHECK (score >= 0 AND score <= 10),
    ai_feedback TEXT -- Detailed feedback generated by Spring AI
);