version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: interview-postgres
    environment:
      POSTGRES_USER: namdx
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: interview_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    container_name: interview-redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

volumes:
  postgres_data: